apiVersion: agent-install.openshift.io/v1beta1
kind: NMStateConfig
metadata:
  name: master-1-network
  namespace: ocp-cli1
  labels:
    cluster-name: ocp-cli1
spec:
  config:
    hostname:
      config: ocp-host2
    interfaces:
    - name: uplink1
      type: ethernet
      state: up
      mac-address: "00:50:56:b3:02:17"
    - name: uplink2
      type: ethernet
      state: up
      mac-address: "00:50:56:b3:67:67"
    - name: bond0
      type: bond
      state: up
      ipv4:
        enabled: true
        dhcp: false
        address:
        - ip: 192.168.31.86
          prefix-length: 24
      link-aggregation:
        mode: active-backup
        port:
        - uplink1
        - uplink2
    dns-resolver:
      config:
        server:
        - 192.168.31.64
    routes:
      config:
      - destination: 0.0.0.0/0
        next-hop-address: 192.168.31.1
        next-hop-interface: bond0
        table-id: 254
  interfaces:
  - name: uplink1
    macAddress: "00:50:56:b3:02:17"
  - name: uplink2
    macAddress: "00:50:56:b3:67:67"
